[project]
name = "nepali-sentiment-analysis-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.0.1",
    "scikit-learn>=1.6.1",
    "streamlit>=1.44.1",
    "torch>=2.6.0",
    "transformers>=4.51.2",
]
